### ISSUE TITLE
ARLAS Configuration becomes ARLAS Exploration Dashboard

### ISSUE THREAD

**Issue by sylvaingaudan** [gisaia/ARLAS-wui-hub#50] opened 2020-11-23 10:31 UTC
ARLAS Configuration becomes ARLAS Exploration Dashboard

![image](https://user-images.githubusercontent.com/35499583/99952051-5714a780-2d7f-11eb-8f39-4613dea83717.png)

**Comment by sebbousquet** [comment] 2020-11-23 14:09
Duplicate of #46

**Closed** 2020-11-24 15:24 UTC
